// resources/js/react/pages/ForgotPassword.tsx
import AlertMessage from '@/components/AlertMessage';
import { useT } from '@/i18n';
import { Modal } from '@inertiaui/modal-react';
import ForgotPasswordForm from '../components/ForgotPasswordForm';
import AuthCardLayout from '../layouts/AuthCardLayout';

interface ForgotPasswordProps {
    status?: string;
    email?: string;
    modal?: boolean;
}

const description =
    'Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.';

/** Password reset request, as a page or a modal. See `Login.tsx` for the reasoning. */
export default function ForgotPassword({
    status,
    email,
    modal,
}: ForgotPasswordProps) {
    const t = useT();

    if (!modal) {
        return (
            <AuthCardLayout
                title={t('Forgot Password')}
                description={t(description)}
            >
                <ForgotPasswordForm email={email} />
            </AuthCardLayout>
        );
    }

    return (
        <Modal maxWidth="md">
            <div className="space-y-4" data-testid="forgot-password-modal">
                <div className="space-y-1.5 text-center">
                    <h2 className="text-2xl font-semibold">
                        {t('Forgot Password')}
                    </h2>
                    <p className="text-muted-foreground text-sm">
                        {t(description)}
                    </p>
                </div>

                {/* The page frame shows this from the shared props; inside the
                    modal it arrives as the modal's own prop. */}
                <AlertMessage
                    message={status}
                    variant="success"
                    data-testid="alert"
                />

                <ForgotPasswordForm email={email} modal />
            </div>
        </Modal>
    );
}

// resources/js/pages/ForgotPassword.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Form, Link, usePage } from '@inertiajs/vue3';
import { computed } from 'vue';
import InputField from '../components/InputField.vue';
import AuthCardLayout from '../layouts/AuthCardLayout.vue';

const page = usePage();
const email = computed(() =>
    page.props.email ? String(page.props.email) : undefined,
);
</script>

<template>
    <AuthCardLayout
        :title="$t('Forgot Password')"
        :description="
            $t(
                'Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.',
            )
        "
    >
        <Form
            :action="route('password.email')"
            method="post"
            class="min-w-sm space-y-3"
            data-testid="forgot-password-form"
            disable-while-processing
            :reset-on-success="['email']"
        >
            <InputField
                name="email"
                type="email"
                :label="$t('Email')"
                :placeholder="$t('Enter your email')"
                :model-value="email"
                required
                autocomplete="email"
            />

            <div class="flex items-center justify-between pt-1">
                <Link
                    :href="route('login')"
                    class="text-sm text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100"
                    data-testid="back-to-login-link"
                >
                    {{ $t('Back to login') }}
                </Link>
                <Button type="submit" data-testid="reset-button">
                    {{ $t('Email Password Reset Link') }}
                </Button>
            </div>
        </Form>
    </AuthCardLayout>
</template>
