// resources/js/pages/Register.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Form, Link } from '@inertiajs/vue3';
import InputField from '../components/InputField.vue';
import SocialiteProviders from '../components/SocialiteProviders.vue';
import AuthCardLayout from '../layouts/AuthCardLayout.vue';
</script>

<template>
  <AuthCardLayout
    :title="$t('Create your account')"
    :description="$t('Sign up for Sauce Base to start building your SaaS')"
  >
    <SocialiteProviders />

    <Form
      :action="route('register')"
      method="post"
      class="space-y-3"
      data-testid="register-form"
      disable-while-processing
      :reset-on-error="['password']"
    >
      <!-- Name -->
      <InputField
        name="name"
        type="text"
        :label="$t('Name')"
        :placeholder="$t('Enter your full name')"
        autocomplete="name"
      />

      <!-- Email -->
      <InputField
        name="email"
        type="email"
        :label="$t('Email')"
        :placeholder="$t('Enter your email')"
        autocomplete="email"
      />

      <!-- Password -->
      <InputField
        name="password"
        type="password"
        :label="$t('Password')"
        :placeholder="$t('Enter your password')"
        autocomplete="new-password"
        required
      />

      <Button type="submit" class="mt-3 w-full" data-testid="register-button">
        {{ $t('Register') }}
      </Button>

      <p class="mt-4 text-center text-sm text-gray-600 dark:text-gray-400">
        {{ $t('Already registered?') }}
        <Link
          :href="route('login')"
          class="font-medium text-indigo-600 hover:text-indigo-500 hover:underline dark:text-indigo-400 dark:hover:text-indigo-300"
          data-testid="login-link"
        >
          {{ $t('Log in') }}
        </Link>
      </p>
    </Form>
  </AuthCardLayout>
</template>

// resources/js/react/pages/Register.tsx
import { useT } from '@/i18n';
import { Modal } from '@inertiaui/modal-react';
import RegisterForm from '../components/RegisterForm';
import AuthCardLayout from '../layouts/AuthCardLayout';

interface RegisterProps {
    modal?: boolean;
}

/** Registration, as a page or a modal. See `Login.tsx` for the reasoning. */
export default function Register({ modal }: RegisterProps) {
    const t = useT();

    if (!modal) {
        return (
            <AuthCardLayout
                title={t('Create your account')}
                description={t(
                    'Sign up for Saucebase to start building your SaaS',
                )}
            >
                <RegisterForm />
            </AuthCardLayout>
        );
    }

    return (
        <Modal maxWidth="md">
            <div className="space-y-4" data-testid="register-modal">
                <div className="space-y-1.5 text-center">
                    <h2 className="text-2xl font-semibold">
                        {t('Create your account')}
                    </h2>
                    <p className="text-muted-foreground text-sm">
                        {t('Sign up for Saucebase to start building your SaaS')}
                    </p>
                </div>

                <RegisterForm modal />
            </div>
        </Modal>
    );
}
